# Generated by Django 2.2.10 on 2021-10-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
